In [3]:
# Импорт библиотеки NumPy с общепринятым сокращением
import numpy as np

In [4]:
print("1. СОЗДАНИЕ МАССИВОВ")

# Создание массива из обычного списка
arr1 = np.array([1, 2, 3, 4, 5])
print("Массив из списка:", arr1)

# Создание массива с помощью zeros
arr2 = np.zeros(5)
print("Массив из нулей:", arr2)

# Создание массива с помощью ones
arr3 = np.ones((3, 3))
print("Массив 3x3 из единиц:\n", arr3)

# Создание массива с помощью arange
arr4 = np.arange(0, 10, 2)  # от 0 до 10 с шагом 2
print("Массив с arange:", arr4)


1. СОЗДАНИЕ МАССИВОВ
Массив из списка: [1 2 3 4 5]
Массив из нулей: [0. 0. 0. 0. 0.]
Массив 3x3 из единиц:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Массив с arange: [0 2 4 6 8]


In [5]:
print("\n2. АТРИБУТЫ МАССИВОВ")
# Демонстрация формы и типа данных
print("Форма arr3:", arr3.shape)
print("Тип данных arr3:", arr3.dtype)
print("Форма arr1:", arr1.shape)
print("Тип данных arr1:", arr1.dtype)


2. АТРИБУТЫ МАССИВОВ
Форма arr3: (3, 3)
Тип данных arr3: float64
Форма arr1: (5,)
Тип данных arr1: int64


In [6]:
print("\n3. ИНДЕКСИРОВАНИЕ И СРЕЗЫ")
# Создание двумерного массива для демонстрации
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Исходная матрица:\n", matrix)

# Получение отдельного элемента
print("Элемент [1,2]:", matrix[1, 2])  # Должно быть 6

# Извлечение подмассива с помощью среза
submatrix = matrix[0:2, 1:3]  # Первые 2 строки, последние 2 столбца
print("Подмассив [0:2, 1:3]:\n", submatrix)


3. ИНДЕКСИРОВАНИЕ И СРЕЗЫ
Исходная матрица:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Элемент [1,2]: 6
Подмассив [0:2, 1:3]:
 [[2 3]
 [5 6]]


In [7]:
print("\n4. ВЕКТОРНЫЕ ОПЕРАЦИИ И СТАТИСТИКИ")
# Поэлементное сложение массивов
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
sum_arr = a + b
print("Поэлементное сложение:", a, "+", b, "=", sum_arr)

# Поэлементное умножение
mult_arr = a * b
print("Поэлементное умножение:", a, "*", b, "=", mult_arr)

# Вычисление статистик
data = np.array([2, 4, 6, 8, 10])
print("Массив для статистик:", data)
print("Среднее значение:", np.mean(data))
print("Стандартное отклонение:", np.std(data))
print("Максимальное значение:", np.max(data))
print("Минимальное значение:", np.min(data))


4. ВЕКТОРНЫЕ ОПЕРАЦИИ И СТАТИСТИКИ
Поэлементное сложение: [1 2 3] + [4 5 6] = [5 7 9]
Поэлементное умножение: [1 2 3] * [4 5 6] = [ 4 10 18]
Массив для статистик: [ 2  4  6  8 10]
Среднее значение: 6.0
Стандартное отклонение: 2.8284271247461903
Максимальное значение: 10
Минимальное значение: 2


In [8]:
print("\n5. ДОПОЛНИТЕЛЬНЫЕ ПРИМЕРЫ")
# Создание массива случайных чисел
random_arr = np.random.randint(0, 100, 10)
print("Массив случайных чисел:", random_arr)
print("Отсортированный массив:", np.sort(random_arr))


5. ДОПОЛНИТЕЛЬНЫЕ ПРИМЕРЫ
Массив случайных чисел: [56 15 12 37 89 48  5 29 87 39]
Отсортированный массив: [ 5 12 15 29 37 39 48 56 87 89]
